import { glob } from "astro/loaders";
import { defineCollection } from "astro:content";
import { z } from "astro/zod";
import { cleanSocialUrl } from "@/lib/utils/socialUrl";

const httpUrl = z.url().refine((value) => {
  const protocol = new URL(value).protocol;
  return protocol === "http:" || protocol === "https:";
}, "URL must use HTTP or HTTPS");
const socialUrl = httpUrl.transform(cleanSocialUrl);

// About collection schema
const aboutCollection = defineCollection({
  loader: glob({ pattern: "**/-*.{md,mdx}", base: "src/content/about" }),
  schema: z.object({
    title: z.string(),
    meta_title: z.string().optional(),
    image: z.string().optional(),
    draft: z.boolean().optional(),
    what_i_do: z.object({
      title: z.string(),
      items: z.array(
        z.object({
          title: z.string(),
          description: z.string(),
        }),
      ),
    }),
  }),
});

// Wedding Directory collection schema
const directoryCollection = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "src/content/directory" }),
  schema: ({ image }) =>
    z.object({
      title: z.string(),
      meta_title: z.string().optional(),
      description: z.string().optional(),
      image: z.union([image(), z.string()]).optional(),
      logo: z.union([image(), z.string()]).optional(),
      website: httpUrl.optional(),
      email: z.email().optional(),
      phone: z.string().optional(),
      address: z.string().optional(),
      location: z.array(z.string()).default(["Australia"]),
      category: z.array(z.string()).default(["Other"]),
      featured: z.boolean().optional(),
      australia_wide: z.boolean().optional(),
      international: z.boolean().optional(),
      // Default true — agents can relay wedding enquiries to this celebrant's
      // public email via /a2a on the worker. Set false to opt out.
      accepts_agent_enquiries: z.boolean().optional(),
      draft: z.boolean().optional(),
      tier: z
        .enum(["registered", "endorsed", "luminary"])
        .default("registered"),
      // Optional public evidence metadata for separate external claims. The
      // tier itself is a credential issued and human verified by Australian
      // Wedding Celebrants, so absent evidence fields never invalidate it.
      // Never put private certificates or personal addresses here.
      tier_evidence_source: z.string().optional(),
      tier_evidence_url: httpUrl.optional(),
      tier_evidence_last_checked: z
        .string()
        .regex(/^\d{4}-\d{2}-\d{2}$/)
        .optional(),
      tier_evidence_note: z.string().optional(),
      slug: z.string().optional(),
      social: z
        .object({
          facebook: socialUrl.optional(),
          instagram: socialUrl.optional(),
          pinterest: socialUrl.optional(),
        })
        .optional(),
      // Premium profile fields — available to all tiers.
      youtube: socialUrl.optional(),
      gallery: z
        .array(z.union([image(), z.string()]))
        .max(3)
        .optional(),
      // Hex colour (e.g. "#faf7f5") applied to the profile page background.
      background_color: z
        .string()
        .regex(
          /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/,
        )
        .optional(),
      // Testimonials — Luminary and Endorsed tiers.
      testimonials: z
        .array(
          z.object({
            quote: z.string(),
            author: z.string(),
            role: z.string().optional(),
          }),
        )
        .max(3)
        .optional(),
      // Year the celebrant started in the profession. Used to auto-generate a
      // "Class of {year}" award on their Trophy Shelf so every celebrant has
      // at least one recognition.
      year_started: z.number().int().optional(),
      // Awards — free-text, playful "staff Christmas party" style recognitions.
      // Title is free text so each award can be as cute or serious as needed.
      // Region is optional (not every award is regional). Year is required so
      // awards can be grouped on /awards/[year]/ pages in future.
      awards: z
        .array(
          z.object({
            title: z.string(),
            emoji: z.string().optional(),
            region: z.string().optional(),
            year: z.number(),
            note: z.string().optional(),
          }),
        )
        .optional(),
    }),
});

// Location blurbs — SEO body copy rendered above the celebrant grid on
// /directory/location/<slug>/ pages. Generated by scripts/generate-location-blurbs.mjs;
// hand-edit the .md files directly, the script preserves existing files.
const locationBlurbsCollection = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "src/content/location-blurbs" }),
  schema: z.object({
    location: z.string(),
    slug: z.string().optional(),
    generated_at: z.string().optional(),
    model: z.string().optional(),
  }),
});

// Pages collection schema
const pagesCollection = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "src/content/pages" }),
  schema: z.object({
    id: z.string().optional(),
    title: z.string(),
    meta_title: z.string().optional(),
    description: z.string().optional(),
    image: z.string().optional(),
    layout: z.string().optional(),
    draft: z.boolean().optional(),
  }),
});

// Export collections
export const collections = {
  about: aboutCollection,
  pages: pagesCollection,
  directory: directoryCollection,
  locationBlurbs: locationBlurbsCollection,
};
